- name: Install MySQL
  yum:
    name:
       - mysql-server
       - mysql
    state: present
- name: Permit MySQL traffic in firewall
  firewalld:
    service: mysql
    permanent: true
    state: enabled

- name: Start and enable MySQL service
  systemd:
    name: mysqld
    state: started
    enabled: true

