- name: Install PHP
  yum:
     name: php
     state: present
- name: Start and enable PHP-FPM service
  systemd:
    name: php-fpm
    state: started
    enabled: true
- name: Permit PHP traffic in firewall
  firewalld:
    service: http
    permanent: true
    state: enabled      
